### ISSUE TITLE
must first ssh manually into machine to use it as obi target

### ISSUE THREAD

**Issue by sandover** [Oblong/obi#107]
. . . and type “yes” to the prompt about whether to add ssh key.

The issue isn't mentioned in the README.

**Comment by EchoAbstract** [comment]
@sandover the normal use case is that you add the host to your `~/.ssh/known_hosts` file when you log in to transfer your ssh key (via `copy-ssh-id`).  We see this since `machine-wizard` deploys our keys for us instead of doing it our selves.

I do think we should have a bit in the README about dealing with SSH issues such as this or the "dreaded" `Host key verification failed` errors.

**Comment by tomjakubowski** [comment]
Can obi detect an ssh "prompt" and bail out?

**Comment by jshrake** [comment]
Duplicate of #42
